import "./globals.css";
import NavBar from "@/components/navbar/NavBar";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`antialiased dark dark:bg-slate-900 container mx-auto`}
      >
        <NavBar />
        {children}
      </body>
    </html>
  );
}
